### ISSUE TITLE
No Login Dialog on First Load Post Deploy

### ISSUE THREAD

**Issue by jon-at-zaneray-dot-com** [potato4d/nuxt-basic-auth-module#103]
After deploying the application protected by this module, the site will not render the Basic Auth login dialog unless a hard reload is done.

The request for / hits the server and gets a 401 response with a www-authenticate: Basic realm, but no login dialog.

**Comment by potato4d** [comment]
@jon-at-zaneray-dot-com 

This is due to the fact that it does not rely on an external database and manages startup based on environment variables and flags.

This in itself is normal behavior, and I don't think switching authentication by an external API or the like is good behavior.

If there are specific behaviors you want to achieve, please suggest them.

**Comment by jon-at-zaneray-dot-com** [comment]
it turns out to be an implementation issue with the browsers and the Service Worker documented here https://bugs.chromium.org/p/chromium/issues/detail?id=623464

**Comment by potato4d** [comment]
oh, thank you for your report!
